/**
 * __VERGE3D_PLAYER__ - delete this comment if you want to edit the player's code
 */
'use strict';

window.addEventListener('load', function() {

var URL = '__URL__Hello World.gltf';
var LOGIC = '__LOGIC__visual_logic.js';
    
var url = URL.replace('__URL__', '') || v3d.AppUtils.getPageParams().load;
if (!url) {
    console.log('No URL specified');
    return;
}

var app = new v3d.App('container', null, 
        new v3d.SimplePreloader({ container: 'container' }));

app.load(url, function() {

    app.enableControls();
    window.v3dApp = app;

    var logicUrl = v3d.AppUtils.getPageParams().logic;
    if (!logicUrl || !isXML(logicUrl))
        logicUrl = LOGIC.replace('__LOGIC__', '') || logicUrl;

    if (logicUrl)
        initPuzzles(logicUrl, runCode);
    else
        runCode();        
});

function isXML(url) {
    return (url.indexOf('.xml') > -1);
}

function initPuzzles(logicUrl, logicCb) {

    logicCb = logicCb || function() {};

    // namespace for communicating with code generated by Puzzles 
    window.v3dApp.ExternalInterface = {};

    // running Puzzles editor
    if (isXML(logicUrl)) {

        var puzzlesDir = '../../puzzles/';
        var puzzlesPath = puzzlesDir + 'puzzles.min.js';
        var puzzlesCSSPath = puzzlesDir + 'puzzles.css';
        var puzzlesMediaDir = puzzlesDir + 'media/';

        v3d.AppUtils.loadScript(puzzlesPath, document.body, function() {
            PE.init(puzzlesMediaDir, logicCb);
        });

        // load Puzzles editor css
        var link = document.createElement('link');
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = puzzlesCSSPath;
        document.head.appendChild(link);

    // loading generated JS code
    } else {
        v3d.AppUtils.loadScript(logicUrl, document.body, logicCb);
    }
}

function runCode() {
    // add your code here, e.g. console.log('Hello, World!');

}

});
